export const books = [
  {id:"hc-verma",title:"Concepts of Physics Vol. 1",author:"H.C. Verma",category:"Competitive Exams",price:420,old:499,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#162f5c,#55749d)'},
  {id:"ncert-maths",title:"NCERT Mathematics Class 12",author:"NCERT",category:"School",price:165,old:180,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#7b4c2e,#d79d58)'},
  {id:"rd-sharma",title:"Mathematics for Class 12",author:"R.D. Sharma",category:"School",price:540,old:625,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#293e2e,#729171)'},
  {id:"organic",title:"Organic Chemistry",author:"Morrison & Boyd",category:"College",price:610,old:750,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#54385f,#b27dbb)'},
  {id:"ncert-physics-12",title:"NCERT Physics Class 12",author:"NCERT",category:"School",price:210,old:240,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"ncert-chemistry-12",title:"NCERT Chemistry Class 12",author:"NCERT",category:"School",price:195,old:225,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"ncert-biology-12",title:"NCERT Biology Class 12",author:"NCERT",category:"School",price:235,old:270,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"ncert-maths-10",title:"NCERT Mathematics Class 10",author:"NCERT",category:"School",price:145,old:165,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"ncert-science-10",title:"NCERT Science Class 10",author:"NCERT",category:"School",price:155,old:175,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"english-grammar",title:"Wren & Martin English Grammar",author:"P.C. Wren",category:"School",price:330,old:390,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"sanskrit-class-10",title:"Sanskrit Vyakaran Class 10",author:"School Edition",category:"School",price:120,old:150,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"social-science-10",title:"Social Science Class 10",author:"NCERT",category:"School",price:180,old:210,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"engineering-maths",title:"Higher Engineering Mathematics",author:"B.S. Grewal",category:"Engineering",price:575,old:690,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"electrical-machines",title:"Electrical Machinery",author:"P.S. Bimbhra",category:"Engineering",price:490,old:575,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"data-structures",title:"Data Structures Using C",author:"Reema Thareja",category:"Engineering",price:410,old:495,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"operating-systems",title:"Operating System Concepts",author:"Silberschatz",category:"Engineering",price:650,old:780,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"dbms",title:"Database System Concepts",author:"Korth",category:"Engineering",price:590,old:700,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"computer-networks",title:"Computer Networking",author:"Kurose & Ross",category:"Engineering",price:620,old:740,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"thermodynamics",title:"Engineering Thermodynamics",author:"P.K. Nag",category:"Engineering",price:455,old:540,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"strength-materials",title:"Strength of Materials",author:"R.K. Bansal",category:"Engineering",price:430,old:510,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"gate-cse",title:"GATE Computer Science Guide",author:"Made Easy",category:"Competitive Exams",price:720,old:850,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"neet-biology",title:"Objective Biology for NEET",author:"Dinesh",category:"Medical",price:680,old:799,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"neet-chemistry",title:"Physical Chemistry for NEET",author:"O.P. Tandon",category:"Medical",price:520,old:620,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"neet-physics",title:"Objective Physics for NEET",author:"D.C. Pandey",category:"Medical",price:610,old:720,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"anatomy",title:"BD Chaurasia Human Anatomy Vol. 1",author:"B.D. Chaurasia",category:"Medical",price:760,old:890,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"physiology",title:"Guyton and Hall Textbook of Medical Physiology",author:"John E. Hall",category:"Medical",price:990,old:1190,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"pharmacology",title:"Essentials of Medical Pharmacology",author:"K.D. Tripathi",category:"Medical",price:850,old:999,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"neet-pyq",title:"NEET Previous Years Questions",author:"Arihant",category:"Medical",price:360,old:430,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"upsc-polity",title:"Indian Polity",author:"M. Laxmikanth",category:"Competitive Exams",price:590,old:699,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"modern-india",title:"A Brief History of Modern India",author:"Spectrum",category:"Competitive Exams",price:380,old:450,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"geography-upsc",title:"Certificate Physical and Human Geography",author:"G.C. Leong",category:"Competitive Exams",price:320,old:380,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"ssc-maths",title:"Quantitative Aptitude",author:"R.S. Aggarwal",category:"Competitive Exams",price:450,old:530,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"reasoning",title:"A Modern Approach to Verbal Reasoning",author:"R.S. Aggarwal",category:"Competitive Exams",price:410,old:490,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"banking-awareness",title:"Banking Awareness",author:"Arihant Experts",category:"Competitive Exams",price:275,old:330,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"railway-guide",title:"Railway Recruitment Exam Guide",author:"Arihant",category:"Competitive Exams",price:310,old:370,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"ctet-guide",title:"CTET Success Master",author:"Arihant",category:"Competitive Exams",price:390,old:460,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"contract-law",title:"Law of Contract",author:"Avtar Singh",category:"Law",price:520,old:620,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"constitution-law",title:"Introduction to the Constitution of India",author:"D.D. Basu",category:"Law",price:680,old:800,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"ipc-bare-act",title:"Bharatiya Nyaya Sanhita Bare Act",author:"Universal",category:"Law",price:190,old:230,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"criminal-law",title:"Criminal Law: Cases and Materials",author:"K.D. Gaur",category:"Law",price:470,old:560,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"jurisprudence",title:"Jurisprudence",author:"N.V. Paranjape",category:"Law",price:420,old:500,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"atomic-habits",title:"Atomic Habits",author:"James Clear",category:"Fiction",price:399,old:499,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"alchemist",title:"The Alchemist",author:"Paulo Coelho",category:"Fiction",price:220,old:299,store:"Khajuri Book House",condition:"Used — Good",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"wings-of-fire",title:"Wings of Fire",author:"A.P.J. Abdul Kalam",category:"Fiction",price:250,old:320,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"god-of-small-things",title:"The God of Small Things",author:"Arundhati Roy",category:"Fiction",price:280,old:350,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"1984",title:"1984",author:"George Orwell",category:"Fiction",price:199,old:260,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"pride-prejudice",title:"Pride and Prejudice",author:"Jane Austen",category:"Fiction",price:180,old:240,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"midnight-children",title:"Midnight’s Children",author:"Salman Rushdie",category:"Fiction",price:320,old:399,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"ikigai",title:"Ikigai",author:"Héctor García & Francesc Miralles",category:"Fiction",price:260,old:350,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"engineering-drawing",title:"Engineering Drawing",author:"N.D. Bhatt",category:"Engineering",price:390,old:470,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"discrete-math",title:"Discrete Mathematics",author:"Kenneth Rosen",category:"Engineering",price:570,old:680,store:"Nahar Book Stall",condition:"Used — Good",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"python-programming",title:"Python Programming",author:"Reema Thareja",category:"Engineering",price:430,old:520,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"java-complete",title:"The Complete Reference: Java",author:"Herbert Schildt",category:"Engineering",price:520,old:620,store:"Shiv Shakti Book Centre",condition:"Used — Good",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"digital-electronics",title:"Digital Design",author:"M. Morris Mano",category:"Engineering",price:490,old:590,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"fluid-mechanics",title:"Fluid Mechanics",author:"R.K. Bansal",category:"Engineering",price:460,old:550,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"notebook-set",title:"Long Notebook Set (4)",author:"Khajuri Stationery",category:"Stationery",price:160,old:200,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"exam-register",title:"Practical Record Register",author:"Student Essentials",category:"Stationery",price:75,old:95,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
  {id:"geometry-box",title:"Geometry Box",author:"Camlin",category:"Stationery",price:95,old:120,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#7b3345,#d77982)'},
  {id:"highlighter-set",title:"Pastel Highlighter Set",author:"Student Essentials",category:"Stationery",price:120,old:150,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#4b4b75,#9494c7)'},
  {id:"sticky-notes",title:"Sticky Notes Pack",author:"Student Essentials",category:"Stationery",price:55,old:75,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#695126,#d1ae60)'},
  {id:"blue-pens",title:"Blue Ball Pen Pack (10)",author:"Student Essentials",category:"Stationery",price:90,old:120,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#17305e,#506b99)'},
  {id:"accountancy-12",title:"Accountancy Class 12",author:"T.S. Grewal",category:"School",price:490,old:580,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#7c4b2b,#d59b58)'},
  {id:"business-studies",title:"Business Studies Class 12",author:"Poonam Gandhi",category:"School",price:360,old:430,store:"Khajuri Book House",condition:"New",color:'linear-gradient(145deg,#283d2d,#6e8d70)'},
  {id:"microeconomics",title:"Introductory Microeconomics",author:"NCERT",category:"School",price:150,old:180,store:"Shiv Shakti Book Centre",condition:"New",color:'linear-gradient(145deg,#593a65,#b37fbe)'},
  {id:"statistics-economics",title:"Statistics for Economics",author:"NCERT",category:"School",price:140,old:170,store:"Nahar Book Stall",condition:"New",color:'linear-gradient(145deg,#174f59,#5da9a2)'},
];

export const stores = [
 {name:'Shiv Shakti Book Centre',tag:'Academic + Competitive',books:'2,400+',distance:'Khajuri Bazaar',rating:'4.7'},
 {name:'Nahar Book Stall',tag:'School + College',books:'1,800+',distance:'Khajuri Bazaar',rating:'4.5'},
 {name:'Khajuri Book House',tag:'Engineering + Medical',books:'3,100+',distance:'Khajuri Bazaar',rating:'4.6'}
];

export const categories = [['📚','School','NCERT, CBSE & state boards'],['🎓','College','University & semester books'],['⚕️','Medical','NEET, MBBS & medical texts'],['🧮','Engineering','JEE, GATE & engineering'],['🔥','Competitive Exams','UPSC, SSC, banking & more'],['⚖️','Law','Bare acts & exam guides'],['📖','Fiction','Novels, classics & new reads'],['📓','Stationery','Everyday academic essentials']];
